name: Build on Push to Master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 10.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore -p:SelfContained=true

    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      uses: EasyDesk/action-dotnet-test@v1.0.0
      with:
        skip-build: true

    - name: Publish Standard Exe
      run: dotnet publish GlucoseTray\GlucoseTray.csproj --configuration Release --no-restore -p:PublishProfile=GlucoseTray\Properties\PublishProfiles\PublishToSingleSelfContainedExe.pubxml

    - name: Publish Slim Exe
      run: dotnet publish GlucoseTray\GlucoseTray.csproj --configuration Release --no-restore -p:PublishProfile=GlucoseTray\Properties\PublishProfiles\PublishToSingleSelfContainedExeWthoutFramework.pubxml

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GlucoseTray-Build
        path: |
          ./GlucoseTray/bin/Release/net10.0-windows7.0/publish/win-x64/GlucoseTray.exe
          ./GlucoseTray/bin/Release/net10.0-windows7.0/publish/win-x64-small/GlucoseTray-Slim.exe
        retention-days: 30
