# To create a release:
# git tag v1.0.0
# git push origin v1.0.0
# or
# use Github UI -> Create Release -> Create New Tag -> v1.0.0 -> Publish Release

name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7.0.1
      with:
        fetch-depth: 0 # Fetch all history for all tags
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v6.0.0
      with:
        dotnet-version: 10.x

    - name: Cache NuGet packages
      uses: actions/cache@v6.1.0
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore -p:SelfContained=true
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Dotnet Tests
      uses: EasyDesk/action-dotnet-test@v1.3.0
      with:
        skip-build: true # optional, default is true
    - name: Publish Standard Exe
      run: dotnet publish GlucoseTray\GlucoseTray.csproj --configuration Release --no-restore -p:PublishProfile=GlucoseTray\Properties\PublishProfiles\PublishToSingleSelfContainedExe.pubxml

    - name: Publish Slim Exe
      run: dotnet publish GlucoseTray\GlucoseTray.csproj --configuration Release --no-restore -p:PublishProfile=GlucoseTray\Properties\PublishProfiles\PublishToSingleSelfContainedExeWthoutFramework.pubxml
    - name: Create a new release note
      uses: softprops/action-gh-release@v3.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: GlucoseTray ${{ github.ref_name }}
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          ./GlucoseTray/bin/Release/net10.0-windows7.0/publish/win-x64/GlucoseTray.exe
          ./GlucoseTray/bin/Release/net10.0-windows7.0/publish/win-x64-small/GlucoseTray-Slim.exe
          ./README.md
